### ISSUE TITLE
Build instructions for XBEs?

### ISSUE THREAD

**Issue by SugaryHull** [brentdc-nz/Half-LifeX#1]
As the title states, I'm wanting to know if it would be possible to provide build instructions for both OpenXDK and possibly even VS2003.

**Comment by brentdc-nz** [comment]
Hi SugaryHull, I can put together a document on how to build each static library and the xbe for VS03 using the XDK, it's actually quite easy and does not really require documentation. However I don't think OpenXDK is capable enough to build Half-LifeX and it was not ported with OpenXDK in mind, someone else will need to fork the code and work on OpenXDK compatibility.

Will post an update when I get around to writing a build document.
